"""Every user-facing string, in English and Brazilian Portuguese.

The language follows Windows' display language unless ``language`` is set in
the config.  Log messages stay in English: they are for diagnosing, and a
single language keeps them searchable.
"""

from __future__ import annotations

import ctypes

_EN = {
    "app": "Game of Life",
    "tip": "Game of Life wallpaper - {state}",
    "tip.hidden": "hidden",
    "tip.paused": "paused",
    "tip.running": "{gps:g} gen/s",
    "tip.resting": "resting ({why})",
    "menu.draw": "Draw on the wallpaper",
    "menu.pause": "Pause",
    "menu.resume": "Resume",
    "menu.soup": "New random soup",
    "menu.clear": "Clear the world",
    "menu.palette": "Next palette",
    "menu.hide": "Hide the wallpaper",
    "menu.show": "Show the wallpaper",
    "menu.startup": "Start with Windows",
    "menu.settings": "Open the settings file",
    "menu.log": "Open the log",
    "menu.exit": "Exit",
    "balloon.title": "Game of Life is running",
    "balloon.body": "It lives behind your desktop icons. Press {hotkey} (or click this icon) to draw on it.",
    "balloon.body.nohotkey": "It lives behind your desktop icons. Click this icon to draw on it.",
    "balloon.noattach.title": "Could not reach the desktop",
    "balloon.noattach.body": "The wallpaper could not be placed behind the icons. Details are in the log.",
    "panel.title": "Game of Life - editor",
    "panel.mode": "Drawing on the desktop. Other windows keep working normally.",
    "panel.play": "Play",
    "panel.pause": "Pause",
    "panel.step": "Step",
    "panel.undo": "Undo",
    "panel.speed": "Speed",
    "panel.per_second": "{gps:.1f} gen/s",
    "panel.status": "generation {gen}  -  {pop} alive  -  {fps} fps",
    "panel.tab.draw": "Draw",
    "panel.tab.world": "World",
    "panel.tab.look": "Look",
    "panel.tool": "Tool",
    "panel.tool.pattern": "Pattern",
    "panel.tool.brush": "Brush",
    "panel.tool.select": "Select",
    "panel.brush": "Brush size",
    "panel.rotate": "Rotate",
    "panel.flip": "Flip",
    "panel.library": "Pattern library",
    "panel.import": "Import file...",
    "panel.paste_rle": "Paste RLE",
    "panel.selection": "Selection",
    "panel.sel.copy": "Copy",
    "panel.sel.cut": "Cut",
    "panel.sel.paste": "Paste",
    "panel.sel.delete": "Delete",
    "panel.sel.rotate": "Rotate",
    "panel.sel.fliph": "Flip H",
    "panel.sel.flipv": "Flip V",
    "panel.sel.fill": "Fill",
    "panel.sel.visible": "Visible",
    "panel.sel.none": "None",
    "panel.sel.export": "Export...",
    "panel.sel.empty": "Nothing selected - drag with the Select tool",
    "panel.sel.info": "{w}x{h} cells at ({x}, {y})",
    "panel.clip": "clipboard {w}x{h}",
    "panel.clear": "Clear",
    "panel.soup": "New soup",
    "panel.density": "Density",
    "panel.skip": "Skip ahead",
    "panel.skip.go": "Go",
    "panel.skip.left": "{n} left",
    "panel.skip.eta": "{n} left, about {s}s",
    "panel.skip.bad": "enter a whole number",
    "panel.rule": "Rule",
    "panel.save_world": "Save world...",
    "panel.load_world": "Load world...",
    "panel.zoom": "Zoom",
    "panel.fit": "Fit",
    "panel.zoom.value": "{z} px per cell",
    "panel.zoom.out": "{k} cells per px",
    "panel.palette": "Palette",
    "panel.cycle": "Change palette every {m:g} min",
    "panel.grid": "Grid",
    "panel.trails": "Trails",
    "panel.trails.value": "{s:.1f} s",
    "panel.smooth": "Smooth cells",
    "panel.frame": "Outline the screens while drawing",
    "panel.hide": "Hide the wallpaper",
    "panel.show": "Show the wallpaper",
    "panel.startup": "Start with Windows",
    "panel.save": "Save as defaults",
    "panel.saved": "Saved to {path}",
    "panel.pin": "Keep this panel on top",
    "panel.close": "Done",
    "panel.hint": "Left click draws, right click erases, middle drag pans, wheel zooms.\n"
                  "Space play/pause  R rotate  F flip  Ctrl+Z undo  Esc done",
    "panel.monitors": "{n} monitor(s), {layer}",
    "panel.import.fail": "Could not read that pattern: {err}",
    "panel.import.ok": "Loaded {w}x{h} - click on the desktop to place it",
    "panel.nothing_to_paste": "The clipboard holds no pattern",
    "panel.too_big": "The selection is too large to rotate in this world",
    "layer.progman": "behind the desktop icons",
    "layer.workerw": "behind the desktop icons (classic layout)",
    "layer.bottom": "a bottom window over the icons (clicks still reach them)",
    "layer.window": "in a window",
    "layer.none": "not on the desktop yet",
    "rules.custom": "Custom...",
    "cat.classic": "Favourites",
    "cat.still": "Still lifes",
    "cat.osc": "Oscillators",
    "cat.ship": "Spaceships",
    "cat.gun": "Guns",
    "cat.puffer": "Puffers, rakes and growth",
    "cat.methuselah": "Methuselahs",
    "cat.wick": "Wicks, fuses and agars",
    "cat.circuit": "Reflectors, eaters and circuitry",
    "cat.synth": "Glider syntheses",
    "cat.big": "Large constructions",
    "cat.other": "Other patterns",
    "cat.mine": "My patterns",
    "lib.search": "Search 4,800 patterns...",
    "lib.none": "No pattern has that name.",
    "lib.more": "Showing the first {n} of {total} - type more to narrow it down.",
    "lib.found.n": "{n} pattern(s) found.",
    "lib.mine.empty": "Put .rle or .cells files in your pattern folder (My folder, below) and press Refresh.",
    "lib.too_big": "Larger than this world: use Open as world.",
    "lib.open_world": "Open as world",
    "lib.folder": "My folder",
    "lib.refresh": "Refresh",
    "lib.keep": "Save to My patterns",
    "lib.kept": "Saved to My patterns as {name}",
    "lib.keep.name": "Name for this pattern:",
    "worlds.too_big": "That pattern is {w} x {h} cells: larger than the {max}-cell limit of a world.",
    "worlds.bad_rule": " - its rule is not supported ({err}); running {rule}",
    "lib.keep.name": "Name for this pattern:",
    "worlds.too_big": "That pattern is {w} x {h} cells: larger than the {max}-cell limit of a world.",
    "worlds.bad_rule": " - its rule is not supported ({err}); running {rule}",
    "lib.kind.classic": "Pattern",
    "lib.kind.still": "Still life",
    "lib.kind.osc": "Oscillator",
    "lib.kind.ship": "Spaceship",
    "lib.kind.gun": "Gun",
    "lib.kind.puffer": "Puffer / growth",
    "lib.kind.methuselah": "Methuselah",
    "lib.kind.wick": "Wick / agar",
    "lib.kind.circuit": "Circuitry",
    "lib.kind.synth": "Glider synthesis",
    "lib.kind.big": "Large construction",
    "lib.kind.other": "Pattern",
    "lib.kind.mine": "My pattern",
    "lib.dir.orthogonal": "orthogonal",
    "lib.dir.diagonal": "diagonal",
    "lib.dir.oblique": "oblique",
    "lib.period": "period {p}",
    "lib.dies": "dies after {n} generations",
    "lib.settles": "settles after {n} generations",
    "lib.size": "{w} x {h} cells, {n} alive",
    "lib.found": "Found by {who}, {year}",
    "lib.found.who": "Found by {who}",
    "lib.found.year": "Found in {year}",
    "lib.sources": "Source: {names}",
    "lib.source.lexicon": "Life Lexicon (S. Silver, CC BY-SA 3.0)",
    "lib.source.lifewiki": "LifeWiki",
    "lib.about.still": "It never changes: every live cell has just the right number of neighbours.",
    "lib.about.osc": "It returns to this exact shape every {p} generations, forever.",
    "lib.about.ship": "It travels across the world, moving {n} cell(s) every {p} generations.",
    "lib.about.gun": "It keeps firing spaceships, forever.",
    "lib.about.puffer": "It travels and leaves a trail behind it, or simply keeps on growing.",
    "lib.about.methuselah": "A small seed that churns for a long time before it settles down.",
    "lib.about.methuselah.n": "A small seed that churns for {n} generations before it settles down.",
    "lib.about.wick": "A long, repeating strip that burns, stretches or tiles space.",
    "lib.about.circuit": "Part of the Game of Life engineering kit: it steers, converts or swallows signals such as gliders.",
    "lib.about.synth": "Gliders arranged so that their collisions build an object.",
    "lib.about.big": "A large construction. Open it as a world to see all of it.",
    "lib.about.other": "A pattern from the collections.",
    "lib.about.dies": "It vanishes completely after {n} generations.",
    "lib.about.classic": "One of the classics.",
    "lib.about.mine": "A pattern from your folder.",
    "worlds": "Worlds",
    "worlds.load": "Load",
    "worlds.save": "Save",
    "worlds.name": "name for this world",
    "worlds.delete": "Delete",
    "worlds.folder": "Folder",
    "worlds.starter": "{name} (example)",
    "worlds.none": "(no saved worlds)",
    "worlds.saved": "World saved as {name}",
    "worlds.loaded": "World: {name} ({w} x {h} cells)",
    "worlds.confirm.delete": "Delete the world “{name}”?",
    "worlds.confirm.overwrite": "A world called “{name}” already exists. Replace it?",
    "worlds.cannot_delete": "The example worlds cannot be deleted.",
    "worlds.fail": "Could not load that world: {err}",
    "worlds.export": "Export RLE...",
    "worlds.import": "Open file...",
    "worlds.size": "World size: {w} x {h} cells",
    "menu.worlds": "Worlds",
    "panel.soup.default": "New soup (back to the default {w} x {h} world)",
}

_PT = {
    "app": "Jogo da Vida",
    "tip": "Papel de parede Jogo da Vida - {state}",
    "tip.hidden": "oculto",
    "tip.paused": "pausado",
    "tip.running": "{gps:g} ger/s",
    "tip.resting": "em repouso ({why})",
    "menu.draw": "Desenhar no papel de parede",
    "menu.pause": "Pausar",
    "menu.resume": "Continuar",
    "menu.soup": "Nova sopa aleatória",
    "menu.clear": "Limpar o mundo",
    "menu.palette": "Próxima paleta",
    "menu.hide": "Ocultar o papel de parede",
    "menu.show": "Mostrar o papel de parede",
    "menu.startup": "Iniciar com o Windows",
    "menu.settings": "Abrir o arquivo de configurações",
    "menu.log": "Abrir o log",
    "menu.exit": "Sair",
    "balloon.title": "O Jogo da Vida está rodando",
    "balloon.body": "Ele vive atrás dos ícones da área de trabalho. Pressione {hotkey} (ou clique neste ícone) para desenhar nele.",
    "balloon.body.nohotkey": "Ele vive atrás dos ícones da área de trabalho. Clique neste ícone para desenhar nele.",
    "balloon.noattach.title": "Não foi possível alcançar a área de trabalho",
    "balloon.noattach.body": "O papel de parede não pôde ser colocado atrás dos ícones. Os detalhes estão no log.",
    "panel.title": "Jogo da Vida - editor",
    "panel.mode": "Desenhando na área de trabalho. As outras janelas continuam funcionando normalmente.",
    "panel.play": "Rodar",
    "panel.pause": "Pausar",
    "panel.step": "Passo",
    "panel.undo": "Desfazer",
    "panel.speed": "Velocidade",
    "panel.per_second": "{gps:.1f} ger/s",
    "panel.status": "geração {gen}  -  {pop} vivas  -  {fps} fps",
    "panel.tab.draw": "Desenhar",
    "panel.tab.world": "Mundo",
    "panel.tab.look": "Visual",
    "panel.tool": "Ferramenta",
    "panel.tool.pattern": "Padrão",
    "panel.tool.brush": "Pincel",
    "panel.tool.select": "Seleção",
    "panel.brush": "Tamanho do pincel",
    "panel.rotate": "Girar",
    "panel.flip": "Espelhar",
    "panel.library": "Biblioteca de padrões",
    "panel.import": "Importar arquivo...",
    "panel.paste_rle": "Colar RLE",
    "panel.selection": "Seleção",
    "panel.sel.copy": "Copiar",
    "panel.sel.cut": "Recortar",
    "panel.sel.paste": "Colar",
    "panel.sel.delete": "Apagar",
    "panel.sel.rotate": "Girar",
    "panel.sel.fliph": "Espelhar H",
    "panel.sel.flipv": "Espelhar V",
    "panel.sel.fill": "Preencher",
    "panel.sel.visible": "Visível",
    "panel.sel.none": "Nenhuma",
    "panel.sel.export": "Exportar...",
    "panel.sel.empty": "Nada selecionado - arraste com a ferramenta Seleção",
    "panel.sel.info": "{w}x{h} células em ({x}, {y})",
    "panel.clip": "área de transferência {w}x{h}",
    "panel.clear": "Limpar",
    "panel.soup": "Nova sopa",
    "panel.density": "Densidade",
    "panel.skip": "Avançar",
    "panel.skip.go": "Ir",
    "panel.skip.left": "faltam {n}",
    "panel.skip.eta": "faltam {n}, cerca de {s}s",
    "panel.skip.bad": "digite um número inteiro",
    "panel.rule": "Regra",
    "panel.save_world": "Salvar mundo...",
    "panel.load_world": "Carregar mundo...",
    "panel.zoom": "Zoom",
    "panel.fit": "Encaixar",
    "panel.zoom.value": "{z} px por célula",
    "panel.zoom.out": "{k} células por px",
    "panel.palette": "Paleta",
    "panel.cycle": "Trocar de paleta a cada {m:g} min",
    "panel.grid": "Grade",
    "panel.trails": "Rastros",
    "panel.trails.value": "{s:.1f} s",
    "panel.smooth": "Células suaves",
    "panel.frame": "Contornar as telas enquanto desenha",
    "panel.hide": "Ocultar o papel de parede",
    "panel.show": "Mostrar o papel de parede",
    "panel.startup": "Iniciar com o Windows",
    "panel.save": "Salvar como padrão",
    "panel.saved": "Salvo em {path}",
    "panel.pin": "Manter este painel no topo",
    "panel.close": "Concluir",
    "panel.hint": "Clique esquerdo desenha, direito apaga, arrastar com o do meio move, roda dá zoom.\n"
                  "Espaço rodar/pausar  R girar  F espelhar  Ctrl+Z desfazer  Esc concluir",
    "panel.monitors": "{n} monitor(es), {layer}",
    "panel.import.fail": "Não foi possível ler esse padrão: {err}",
    "panel.import.ok": "Carregado {w}x{h} - clique na área de trabalho para posicionar",
    "panel.nothing_to_paste": "A área de transferência não contém um padrão",
    "panel.too_big": "A seleção é grande demais para girar neste mundo",
    "layer.progman": "atrás dos ícones da área de trabalho",
    "layer.workerw": "atrás dos ícones da área de trabalho (layout clássico)",
    "layer.bottom": "janela no fundo, sobre os ícones (os cliques ainda chegam a eles)",
    "layer.window": "em uma janela",
    "layer.none": "ainda não está na área de trabalho",
    "rules.custom": "Personalizada...",
    "cat.classic": "Favoritos",
    "cat.still": "Vidas estáticas",
    "cat.osc": "Osciladores",
    "cat.ship": "Naves espaciais",
    "cat.gun": "Canhões",
    "cat.puffer": "Puffers, rastelos e crescimento",
    "cat.methuselah": "Matusaléns",
    "cat.wick": "Pavios, fusíveis e ágares",
    "cat.circuit": "Refletores, comedores e circuitos",
    "cat.synth": "Sínteses com planadores",
    "cat.big": "Construções grandes",
    "cat.other": "Outros padrões",
    "cat.mine": "Meus padrões",
    "lib.search": "Buscar entre 4.800 padrões...",
    "lib.none": "Nenhum padrão com esse nome.",
    "lib.more": "Mostrando os primeiros {n} de {total} - digite mais para filtrar.",
    "lib.found.n": "{n} padrão(ões) encontrado(s).",
    "lib.mine.empty": "Coloque arquivos .rle ou .cells na sua pasta de padrões (Minha pasta, abaixo) e clique em Atualizar.",
    "lib.too_big": "Maior que este mundo: use Abrir como mundo.",
    "lib.open_world": "Abrir como mundo",
    "lib.folder": "Minha pasta",
    "lib.refresh": "Atualizar",
    "lib.keep": "Guardar em Meus padrões",
    "lib.kept": "Guardado em Meus padrões como {name}",
    "lib.keep.name": "Nome para este padrão:",
    "worlds.too_big": "Esse padrão tem {w} x {h} células: maior que o limite de {max} de um mundo.",
    "worlds.bad_rule": " - a regra dele não é suportada ({err}); rodando {rule}",
    "lib.keep.name": "Nome para este padrão:",
    "worlds.too_big": "Esse padrão tem {w} x {h} células: maior que o limite de {max} de um mundo.",
    "worlds.bad_rule": " - a regra dele não é suportada ({err}); rodando {rule}",
    "lib.kind.classic": "Padrão",
    "lib.kind.still": "Vida estática",
    "lib.kind.osc": "Oscilador",
    "lib.kind.ship": "Nave espacial",
    "lib.kind.gun": "Canhão",
    "lib.kind.puffer": "Puffer / crescimento",
    "lib.kind.methuselah": "Matusalém",
    "lib.kind.wick": "Pavio / ágar",
    "lib.kind.circuit": "Circuito",
    "lib.kind.synth": "Síntese com planadores",
    "lib.kind.big": "Construção grande",
    "lib.kind.other": "Padrão",
    "lib.kind.mine": "Meu padrão",
    "lib.dir.orthogonal": "ortogonal",
    "lib.dir.diagonal": "diagonal",
    "lib.dir.oblique": "oblíqua",
    "lib.period": "período {p}",
    "lib.dies": "some após {n} gerações",
    "lib.settles": "estabiliza após {n} gerações",
    "lib.size": "{w} x {h} células, {n} vivas",
    "lib.found": "Descoberto por {who}, {year}",
    "lib.found.who": "Descoberto por {who}",
    "lib.found.year": "Descoberto em {year}",
    "lib.sources": "Fonte: {names}",
    "lib.source.lexicon": "Life Lexicon (S. Silver, CC BY-SA 3.0)",
    "lib.source.lifewiki": "LifeWiki",
    "lib.about.still": "Nunca muda: cada célula viva tem exatamente o número certo de vizinhas.",
    "lib.about.osc": "Volta exatamente a esta forma a cada {p} gerações, para sempre.",
    "lib.about.ship": "Viaja pelo mundo, avançando {n} célula(s) a cada {p} gerações.",
    "lib.about.gun": "Dispara naves sem parar, para sempre.",
    "lib.about.puffer": "Viaja deixando um rastro para trás, ou simplesmente não para de crescer.",
    "lib.about.methuselah": "Uma semente pequena que se agita por muito tempo antes de se acalmar.",
    "lib.about.methuselah.n": "Uma semente pequena que se agita por {n} gerações antes de se acalmar.",
    "lib.about.wick": "Uma faixa longa e repetitiva que queima, se estica ou preenche o espaço.",
    "lib.about.circuit": "Peça da engenharia do Jogo da Vida: desvia, converte ou engole sinais como planadores.",
    "lib.about.synth": "Planadores posicionados para que suas colisões construam um objeto.",
    "lib.about.big": "Uma construção grande. Abra-a como mundo para vê-la inteira.",
    "lib.about.other": "Um padrão das coleções.",
    "lib.about.dies": "Desaparece por completo após {n} gerações.",
    "lib.about.classic": "Um dos clássicos.",
    "lib.about.mine": "Um padrão da sua pasta.",
    "worlds": "Mundos",
    "worlds.load": "Carregar",
    "worlds.save": "Salvar",
    "worlds.name": "nome para este mundo",
    "worlds.delete": "Excluir",
    "worlds.folder": "Pasta",
    "worlds.starter": "{name} (exemplo)",
    "worlds.none": "(nenhum mundo salvo)",
    "worlds.saved": "Mundo salvo como {name}",
    "worlds.loaded": "Mundo: {name} ({w} x {h} células)",
    "worlds.confirm.delete": "Excluir o mundo “{name}”?",
    "worlds.confirm.overwrite": "Já existe um mundo chamado “{name}”. Substituir?",
    "worlds.cannot_delete": "Os mundos de exemplo não podem ser excluídos.",
    "worlds.fail": "Não foi possível carregar esse mundo: {err}",
    "worlds.export": "Exportar RLE...",
    "worlds.import": "Abrir arquivo...",
    "worlds.size": "Tamanho do mundo: {w} x {h} células",
    "menu.worlds": "Mundos",
    "panel.soup.default": "Nova sopa (de volta ao mundo padrão de {w} x {h})",
}

_CATEGORIES_PT = {
    "Still lifes": "Vidas estáticas", "Oscillators": "Osciladores", "Spaceships": "Naves",
    "Methuselahs": "Matusaléns", "Guns & growth": "Canhões e crescimento",
}

RULES = (
    ("Conway (B3/S23)", "B3/S23"),
    ("HighLife (B36/S23)", "B36/S23"),
    ("Day & Night (B3678/S34678)", "B3678/S34678"),
    ("Seeds (B2/S)", "B2/S"),
    ("Life without Death (B3/S012345678)", "B3/S012345678"),
    ("Maze (B3/S12345)", "B3/S12345"),
    ("2x2 (B36/S125)", "B36/S125"),
    ("Morley (B368/S245)", "B368/S245"),
    ("Diamoeba (B35678/S5678)", "B35678/S5678"),
    ("Replicator (B1357/S1357)", "B1357/S1357"),
)

_language = "en"


def detect() -> str:
    try:
        langid = ctypes.windll.kernel32.GetUserDefaultUILanguage()
        if langid & 0x3FF == 0x16:                 # LANG_PORTUGUESE
            return "pt"
    except (AttributeError, OSError):
        pass
    return "en"


def set_language(choice: str = "auto") -> str:
    global _language
    _language = detect() if choice in ("", "auto", None) else ("pt" if choice.startswith("pt") else "en")
    return _language


def t(key: str, **values) -> str:
    table = _PT if _language == "pt" else _EN
    text = table.get(key) or _EN.get(key) or key
    try:
        return text.format(**values) if values else text
    except (KeyError, ValueError, IndexError):
        return text


_PT_DIGITS = str.maketrans({",": ".", ".": ","})


def num(value, decimals: int = 0) -> str:
    """A number with thousands separators the way the chosen language writes them."""
    text = f"{value:,.{decimals}f}"
    if _language == "pt":
        text = text.translate(_PT_DIGITS)
    return text


def category(name: str) -> str:
    """A library category's name: the keys of core.library.CATEGORIES (or an old title)."""
    key = f"cat.{name}"
    if key in _EN:
        return t(key)
    return _CATEGORIES_PT.get(name, name) if _language == "pt" else name


def language() -> str:
    return _language
